// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/deadrop/v1/exchange.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExchangeRequest represents an RFC 8693 token exchange request
type ExchangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OAuth token to exchange
	SubjectToken string `protobuf:"bytes,1,opt,name=subject_token,json=subjectToken,proto3" json:"subject_token,omitempty"`
	// Type of subject token (e.g., "urn:ietf:params:oauth:token-type:jwt")
	SubjectTokenType string `protobuf:"bytes,2,opt,name=subject_token_type,json=subjectTokenType,proto3" json:"subject_token_type,omitempty"`
	// Requested token type (e.g., "urn:ietf:params:oauth:token-type:jwt")
	RequestedTokenType string `protobuf:"bytes,3,opt,name=requested_token_type,json=requestedTokenType,proto3" json:"requested_token_type,omitempty"`
	// Target audience(s) - multiple values per RFC 8693
	Audience []string `protobuf:"bytes,4,rep,name=audience,proto3" json:"audience,omitempty"`
	// Optional scopes
	Scope []string `protobuf:"bytes,5,rep,name=scope,proto3" json:"scope,omitempty"`
	// Resource URIs - multiple values per RFC 8693
	Resource      []string `protobuf:"bytes,6,rep,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_carabiner_deadrop_v1_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_deadrop_v1_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_deadrop_v1_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRequest) GetSubjectToken() string {
	if x != nil {
		return x.SubjectToken
	}
	return ""
}

func (x *ExchangeRequest) GetSubjectTokenType() string {
	if x != nil {
		return x.SubjectTokenType
	}
	return ""
}

func (x *ExchangeRequest) GetRequestedTokenType() string {
	if x != nil {
		return x.RequestedTokenType
	}
	return ""
}

func (x *ExchangeRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *ExchangeRequest) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ExchangeRequest) GetResource() []string {
	if x != nil {
		return x.Resource
	}
	return nil
}

// ExchangeResponse represents the response from token exchange
type ExchangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The access token issued by the authorization server
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The type of token issued (e.g., "urn:ietf:params:oauth:token-type:jwt")
	IssuedTokenType string `protobuf:"bytes,2,opt,name=issued_token_type,json=issuedTokenType,proto3" json:"issued_token_type,omitempty"`
	// The type of the token (e.g., "Bearer")
	TokenType string `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// The lifetime in seconds of the access token
	ExpiresIn     int64 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_carabiner_deadrop_v1_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_deadrop_v1_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_deadrop_v1_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeResponse) GetIssuedTokenType() string {
	if x != nil {
		return x.IssuedTokenType
	}
	return ""
}

func (x *ExchangeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// ErrorResponse represents an OAuth 2.0 error response
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code as defined in RFC 6749
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Human-readable description of the error
	ErrorDescription string `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_carabiner_deadrop_v1_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_deadrop_v1_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_deadrop_v1_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorResponse) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

var File_carabiner_deadrop_v1_exchange_proto protoreflect.FileDescriptor

const file_carabiner_deadrop_v1_exchange_proto_rawDesc = "" +
	"\n" +
	"#carabiner/deadrop/v1/exchange.proto\x12\x14carabiner.deadrop.v1\"\xe4\x01\n" +
	"\x0fExchangeRequest\x12#\n" +
	"\rsubject_token\x18\x01 \x01(\tR\fsubjectToken\x12,\n" +
	"\x12subject_token_type\x18\x02 \x01(\tR\x10subjectTokenType\x120\n" +
	"\x14requested_token_type\x18\x03 \x01(\tR\x12requestedTokenType\x12\x1a\n" +
	"\baudience\x18\x04 \x03(\tR\baudience\x12\x14\n" +
	"\x05scope\x18\x05 \x03(\tR\x05scope\x12\x1a\n" +
	"\bresource\x18\x06 \x03(\tR\bresource\"\x9f\x01\n" +
	"\x10ExchangeResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12*\n" +
	"\x11issued_token_type\x18\x02 \x01(\tR\x0fissuedTokenType\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\"R\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x02 \x01(\tR\x10errorDescriptionB\xc7\x01\n" +
	"\x18com.carabiner.deadrop.v1B\rExchangeProtoP\x01Z*github.com/carabiner-dev/deadrop/api/v1;v1\xa2\x02\x03CDX\xaa\x02\x14Carabiner.Deadrop.V1\xca\x02\x14Carabiner\\Deadrop\\V1\xe2\x02 Carabiner\\Deadrop\\V1\\GPBMetadata\xea\x02\x16Carabiner::Deadrop::V1b\x06proto3"

var (
	file_carabiner_deadrop_v1_exchange_proto_rawDescOnce sync.Once
	file_carabiner_deadrop_v1_exchange_proto_rawDescData []byte
)

func file_carabiner_deadrop_v1_exchange_proto_rawDescGZIP() []byte {
	file_carabiner_deadrop_v1_exchange_proto_rawDescOnce.Do(func() {
		file_carabiner_deadrop_v1_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_deadrop_v1_exchange_proto_rawDesc), len(file_carabiner_deadrop_v1_exchange_proto_rawDesc)))
	})
	return file_carabiner_deadrop_v1_exchange_proto_rawDescData
}

var file_carabiner_deadrop_v1_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_carabiner_deadrop_v1_exchange_proto_goTypes = []any{
	(*ExchangeRequest)(nil),  // 0: carabiner.deadrop.v1.ExchangeRequest
	(*ExchangeResponse)(nil), // 1: carabiner.deadrop.v1.ExchangeResponse
	(*ErrorResponse)(nil),    // 2: carabiner.deadrop.v1.ErrorResponse
}
var file_carabiner_deadrop_v1_exchange_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_carabiner_deadrop_v1_exchange_proto_init() }
func file_carabiner_deadrop_v1_exchange_proto_init() {
	if File_carabiner_deadrop_v1_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_deadrop_v1_exchange_proto_rawDesc), len(file_carabiner_deadrop_v1_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_deadrop_v1_exchange_proto_goTypes,
		DependencyIndexes: file_carabiner_deadrop_v1_exchange_proto_depIdxs,
		MessageInfos:      file_carabiner_deadrop_v1_exchange_proto_msgTypes,
	}.Build()
	File_carabiner_deadrop_v1_exchange_proto = out.File
	file_carabiner_deadrop_v1_exchange_proto_goTypes = nil
	file_carabiner_deadrop_v1_exchange_proto_depIdxs = nil
}
